### PR TITLE
UNLOAD, SET TBLPROPERTIES, SERDEPROPERTIES, EXECUTE USING, SET LOCATION, DELIMITED, EXTENDED / FORMATTED

### PR DESCRIPTION
**Pull request by jonathanlehto**
Some updates, I tried to find references and included them below.  I'm not all too familiar with this repo. so feedback would be appreciated.

If needed, I can look into breaking out these changes into separate PR's.

SET TBLPROPERTIES -- https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-tblproperties.html#set-tblproperties

Hive Delimited Properties -- https://spark.apache.org/docs/latest/sql-ref-syntax-hive-format.html

Hive SERDEPROPERTIES -- https://spark.apache.org/docs/3.0.1/sql-ref-syntax-ddl-create-table-hiveformat.html

Hive EXTENDED / FORMATTED -- https://docs.cloudera.com/cdw-runtime/cloud/materialized-view-commands/topics/hive_describe_materialized_view.html

Added support for DESC version of DESCRIBE

EXECUTE USING -- https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-EXECUTING-DYN

Unload -- https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html
  Athena only, should this be its own dialect?

Athena SET LOCATION -- https://docs.aws.amazon.com/athena/latest/ug/alter-table-set-location.html
  Doesn't require SET, also may be Athena only

Included is a possible bugfix where supporting columns after partition could consume a query

### CODE REVIEW

**Comment by alamb** [comment]
Hi @jonathanlehto  -- thank you for the contribution and I apologize for the delay in reviews. 

If you could please split this PR into smaller ones for easier review I would be most appreciative -- it will be much easier for me to verify that each feature is properly tested and documented in smaller PRs rather than one large one

**Comment by alamb** [comment]
Marking as Draft to signify this PR is no longer waiting on review. Please mark it as ready for review when it is ready for another look.

**Comment by jonathanlehto** [comment]
Okay, this pull request has been split into the following.  I'll leave this this on draft for now

https://github.com/sqlparser-rs/sqlparser-rs/pull/1150
https://github.com/sqlparser-rs/sqlparser-rs/pull/1151
https://github.com/sqlparser-rs/sqlparser-rs/pull/1152
https://github.com/sqlparser-rs/sqlparser-rs/pull/1153
https://github.com/sqlparser-rs/sqlparser-rs/pull/1154
https://github.com/sqlparser-rs/sqlparser-rs/pull/1155
https://github.com/sqlparser-rs/sqlparser-rs/pull/1156
https://github.com/sqlparser-rs/sqlparser-rs/pull/1157

**Comment by alamb** [comment]
> Okay, this pull request has been split into the following. I'll leave this this on draft for now

Thank you very much 🙏

**Comment by jonathanlehto** [comment]
Most of the split pr's are in.  This pr is no longer necessary as a reference, closing..

**Pull request closed without merging**
