### PR TITLE
added AWS Redshift keywords

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
Hi guys,
Many thanks to you for a project!
I'm working on a redshift parser using your library and found no way how to extend keywords besides adding them directly to your  repo

### CODE REVIEW

**Review by AugustoFKL — APPROVED** [review]
Seems ok to me if the tests pass as soon as it is allowed.

@alamb

**Comment by alamb** [comment]
I took the liberty of merging up from main to get CI to pass

**Comment by alamb** [comment]
Hi @AndrewChubatiuk  -- the tests are failing on this PR -- can you please fix them?

**Comment by alamb** [comment]
This PR has some feedback that needs implementing, so marking it as draft. Please mark it as ready for review when it is next ready.

**Pull request closed without merging**
