### PR TITLE
feat: Add custom operator

### PR DESCRIPTION
**Pull request by max-sixty**
From #863

- It doesn't parse anything — I'm not sure how to parse ` SELECT 'a' REGEXP '^[a-d]';` with `REGEXP` as the operator... (but fine for my narrow purpose)
- If we need tests, where would I add them?

### CODE REVIEW

**Comment by ankrgyl** [comment]
Apologies if I'm missing some context, but what is the purpose of this new operator? Is it so you can build up a tree manually with a custom string at a certain position?

**Comment by max-sixty** [comment]
Yes, we'd like to write:

```
 SELECT 'a' REGEXP '^[a-d]';
```

...which is how MySQL & Sqllite do regex...

**Comment by ankrgyl** [comment]
I'll add some comments on the task!

**Review by alamb — APPROVED** [review]
I think this looks good to me -- thank you @max-sixty 
I took the liberty of adding a docstring to try and make the use case clearer (and avoid it being deleted by accident in the future

**Comment by max-sixty** [comment]
Thanks @alamb !

**Comment by alamb** [comment]
BTW I expect to release the next version of sqlparser to crates.io today, which will include this fix

**Pull request merged**
