### PR TITLE
Support for postgres String Constants with Unicode Escapes

### PR DESCRIPTION
**Pull request by lovasoa**
fixes https://github.com/sqlparser-rs/sqlparser-rs/issues/1354

### CODE REVIEW

**Comment by lovasoa** [comment]
I think the failed "lint" test is not related to the changes in this PR.

**Comment by git-hulk** [comment]
> I think the failed "lint" test is not related to the changes in this PR.

Yes, I also mentioned in https://github.com/sqlparser-rs/sqlparser-rs/pull/1353#discussion_r1693982851

**Review by git-hulk — APPROVED** [review]

**Comment by lovasoa** [comment]
I opened a separate PR for the clippy errors: https://github.com/sqlparser-rs/sqlparser-rs/pull/1357

**Comment by lovasoa** [comment]
@alamb , I just merged the ci fixes from main, the CI passes, this should be good to merge.

**Review by alamb — APPROVED** [review]
Thanks @lovasoa  and @git-hulk

**Pull request merged**
