### PR TITLE
fix: unnest join constraint with alias parsing for BigQuery dialect

### PR DESCRIPTION
**Pull request by Ziinc**
This PR fixes a parsing bug for the BigQuery Dialect. 
The expected outcome is for the following statement to be parsed with join constraints:
```sql
select * from t1 join unnest(t1.col) as f1 on  c1 = 123
```
However, this statement would result in the following error:
```
ParserError("Expected end of statement, found: c1")
```
Closer inspection revealed that the following ast was produced for the join table factor 

```
UNNEST { 
  alias: Some(TableAlias { name: Ident { value: "f", quote_style: None }, columns: [] }), 
  array_expr: CompoundIdentifier([Ident { value: "t1", quote_style: None }, Ident { value: "a", quote_style: None }]), 
  with_offset: false, 
  with_offset_alias: Some(Ident { value: "ON", quote_style: None }) 
}
```
As you can see, the `with_offset_alias` parses the `ON` keyword despite the `with_offset` being false.

To replicate this behaviour, I added a failing test that verifies this behaviour difference
```
thread 'parse_join_constraint_unnest' panicked at 'called `Result::unwrap()` on an `Err` value: ParserError("Expected end of statement, found: c1")', src/test_utils.rs:86:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test parse_join_constraint_unnest ... FAILED
```

This fix uses the boolean check to determine if the subsequent optional alias should be parsed.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks great -- thank you @Ziinc

**Comment by alamb** [comment]
@Ziinc  there are some CI failures on this PR -- can you please resolve them?

**Comment by Ziinc** [comment]
@alamb I've fixed the lint error. For the test case, it seems like the inline comments for the tested cases were off, and the last case that I removed should actually raise a ParserError, since an alias + WITH OFFSET alias without a WITH OFFSET clause does not make sense.

**Review by alamb — APPROVED** [review]
Makes sense to me -- thank you @Ziinc

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @Ziinc

**Pull request merged**
