### PR TITLE
fix(Dialect): fix a typo (precendence -> precedence)

### PR DESCRIPTION
**Pull request by SARDONYX-sard**

### CODE REVIEW

**Review by AugustoFKL — APPROVED** [review]
lgtm

TBH not sure wether we should remove this variable. Is it used anywhere else? The underscore before the name is quite a bother

**Comment by SARDONYX-sard** [comment]
> lgtm
> 
> TBH not sure wether we should remove this variable. Is it used anywhere else? The underscore before the name is quite a bother

Thanks for the reply.

VSCode told us.
It appears to be used only for testing.
 - https://github.com/sqlparser-rs/sqlparser-rs/blob/main/tests/sqlparser_custom_dialect.rs#L72

**Comment by AugustoFKL** [comment]
@SARDONYX-sard could you please remove it?

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
> TBH not sure wether we should remove this variable. Is it used anywhere else? The underscore before the name is quite a bother

I think `_precedence` is part of the `Dialect` trait definition. As you say I don't think it is actually used but it is passed to the trait in the parser, and users may have implemented the `Dialect` trait in their own projects and used the `precedence` argument.

https://github.com/sqlparser-rs/sqlparser-rs/blob/3f874f4ab8ad17f5149b57183436a4cdf4cf0704/src/parser.rs#L1583

Here are the other uses
https://github.com/search?q=repo%3Asqlparser-rs%2Fsqlparser-rs%20parse_infix&type=code


Thus I think we should keep it in the trait

**Comment by alamb** [comment]
Thank you @SARDONYX-sard  and @AugustoFKL

**Pull request merged**
