### PR TITLE
chore: fix clippy error in ci

### PR DESCRIPTION
**Pull request by togami2864**
To avoid clippy error like #802 in CI.
Maybe this ci error has affected by https://github.com/rust-lang/rust-clippy/pull/10265

### CODE REVIEW

**Comment by togami2864** [comment]
I fixed this but it also might be good simply disable this rule.

**Review by AugustoFKL — APPROVED** [review]
Well, only linter fixes

Thanks!

**Comment by AugustoFKL** [comment]
@alamb, can this be approved before other PRs, please?

It seems like Rust had an update, so other PR's linters are failing.

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @togami2864  and @AugustoFKL

**Pull request merged**
