### PR TITLE
Support mssql json and xml extensions

### PR DESCRIPTION
**Pull request by lovasoa**
Adds support for SQL syntax like 

```sql
SELECT * FROM t FOR JSON PATH, ROOT('x'), INCLUDE_NULL_VALUES
SELECT * FROM t FOR XML PATH('x'), ROOT('y'), ELEMENTS
```

fixes https://github.com/sqlparser-rs/sqlparser-rs/issues/1042

See the documentation for the FOR clause here: https://learn.microsoft.com/en-us/sql/t-sql/queries/select-for-clause-transact-sql?view=sql-server-ver16

### CODE REVIEW

**Comment by lovasoa** [comment]
@alamb : I'd love to get your feedback on this. I'm adding more JSON-related features to [SQLPage](https://github.com/lovasoa/SQLpage), and missing json support is blocking for mssql users.

I also added support for the XML syntax while I was at it.

**Comment by alamb** [comment]
Thanks @lovasoa  - I hope to find time to review this over the next few days

**Comment by lovasoa** [comment]
@alamb , did you find the time to give a quick look ? I'd like to release a new version of sqlpage with this :)

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @lovasoa

**Comment by lovasoa** [comment]
Great, thank you @alamb !

**Pull request merged**
