### PR TITLE
Support for Snowflake ASOF joins

### PR DESCRIPTION
**Pull request by jmhain**
Snowflake just gained `ASOF` joins. This PR adds support for parsing these.

### CODE REVIEW

**Review by iffyio — APPROVED** [review]
LGTM! cc @alamb

**Review by alamb — APPROVED** [review]
Looks great -- thank you @jmhain

**Comment by alamb** [comment]
Looks like this PR has a conflict, but once that is resolved it should be good to go

**Comment by jmhain** [comment]
@alamb Conflict resolved

**Comment by alamb** [comment]
🚀

**Pull request merged**
