### PR TITLE
BigQuery: support for ANY_VALUE HAVING clause

### PR DESCRIPTION
**Pull request by jmhain**

### CODE REVIEW

**Review by iffyio — APPROVED** [review]
LGTM! @alamb

**Review by alamb — APPROVED** [review]
Thank you (again) @jmhain and @iffyio

**Comment by alamb** [comment]
This PR seems to have a conflict which prevents me from merging it

**Comment by jmhain** [comment]
@alamb conflicts resolved

**Comment by alamb** [comment]
Thanks again

**Pull request merged**
