### PR TITLE
feat: Initial support for DECLARE (cursors)

### PR DESCRIPTION
**Pull request by ovr**
Hello!

It requires support for arguments, but it's a good initial point for supporting `DECLARE`.

Thanks

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @ovr

**Comment by alamb** [comment]
@ovr thank you -- For some reason github says this PR has a conflict -- can you possibly do so and I'll merge it in?

Thanks again!


Screen Shot 2022-06-04 at 2 28 21 PM

**Comment by ovr** [comment]
@alamb Rebased ✅

**Review by alamb — APPROVED** [review]
Looks great -- thanks agian @ovr

**Pull request merged**
