### PR TITLE
Support identifiers beginning with digits in MySQL

### LINKED ISSUE #804: Incorrect parsing literals that consisting of digits and letters, beginning with digits
It seems when parsing a literal beginning with digits, the sql parser simply ends this token when meets a non-numeric character

see https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/tokenizer.rs#L547

For example, `123foobar` would be parsed into a number token `123` and a word token `foobar` instead of one word token `123foobar`.

And `123foobar456` would be parsed into `123` and `foobar456`

### PR DESCRIPTION
**Pull request by AviRaboah**
Closes #804.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @AviRaboah  and @ankrgyl  -- the only other thing I suggest is a negative case for the exponent case

For example, can we add a test case to make sure `123e4`  can not be used as an identifier? (at least that is my understanding of the limitiation)

**Review by alamb — APPROVED** [review]

**Comment by AviRaboah** [comment]
> Thank you @AviRaboah and @ankrgyl -- the only other thing I suggest is a negative case for the exponent case
> 
> For example, can we add a test case to make sure `123e4` can not be used as an identifier? (at least that is my understanding of the limitation)

It can't be used  as an identifier, because I added a condition which check that the exponent part is not empty in order to check if it's an identifier. in your test case the exponent part will be > 0 and because of that it will end as an exponent number. but i'll add a test case to cover this.

**Comment by AviRaboah** [comment]
Hi @alamb, 
I added the test :)

**Review by alamb — COMMENTED** [review]
Thank you @AviRaboah and @ankrgyl

**Review by alamb — APPROVED** [review]

**Pull request merged**
