### PR TITLE
add support for MAX as a character length

### PR DESCRIPTION
**Pull request by lovasoa**
See:
https://learn.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16
https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16

### CODE REVIEW

**Comment by lustefaniak** [comment]
Also Redshift supports that syntax

**Comment by lovasoa** [comment]
Good, let's kill two birds with one stone :)

@alamb , if you could have a look at it... The changes on this one are minimal.

**Review by alamb — APPROVED** [review]
Makes sense to me -- thank you @lovasoa  and @lustefaniak

**Comment by lovasoa** [comment]
thanks @alamb ! That'll be in SQLPage's next version.

**Pull request merged**
