### PR TITLE
Improve tokenizer error

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by koushiro** [comment]
@alamb @Dandandan PTAL

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @koushiro  -- looks like an improvement to me 👍 

Can you please add at least one test case demonstrating the functionality? The rationale is to ensure that if someone changes / breaks this functionality in the future tests will catch it.

**Comment by koushiro** [comment]
> Can you please add at least one test case demonstrating the functionality? The rationale is to ensure that if someone changes / breaks this functionality in the future tests will catch it.

I am not sure about what your meaning, test case about what?

**Comment by alamb** [comment]
> I am not sure about what your meaning, test case about what?

Sorry for not being clear -- I guess I was thinking something that ensures that `TokenizerError` implements `std::error::Error` -- the rationale being that if someone removed the line

```rust
impl std::error::Error for TokenizerError {}
```

by accident in a future PR we would likely never know the difference as no tests would fail.

**Review by alamb — APPROVED** [review]
Thanks @koushiro

**Pull request merged**
