### PR TITLE
Rename `sqlparser_derive` to `sqlparser_procmacro`, document features

### PR DESCRIPTION
**Pull request by alamb**
Follow on from https://github.com/sqlparser-rs/sqlparser-rs/pull/765

rename crate to sqlparser_procmacro to be more consistent with other crates in the rust ecosystem

### CODE REVIEW

**Comment by alamb** [comment]
I plan to merge this once CI passes as I then plan to add CI tests for the other crate features

**Comment by alamb** [comment]
cc @tustvold

**Comment by tustvold** [comment]
`_derive` is more consistent with the ecosystem as whole for a derive macro?

**Comment by alamb** [comment]
@tustvold  notes prior art `serde_derive`, `parquet_derive`, etc -- will leave this alone

**Pull request closed without merging**
