### PR TITLE
Add TrimWhereField for `parse_trim_expr`

### PR DESCRIPTION
**Pull request by ever0de**

### CODE REVIEW

**Comment by Dandandan** [comment]
Changes look good, could you add some tests @ever0de ?

**Review by alamb — COMMENTED** [review]
Hi @ever0de  thank you for the contribution! 

Can you please add tests, as a way of documentation:
1. The positive cases (e.g. `TRIM(LEADING FROM foo)
2. The negative cases (e.g. `TRIM(FOO from FOO)`

Thanks!

**Comment by ever0de** [comment]
> Changes look good, could you add some tests @ever0de ?

Some tests have been added to #331.
I'll add a case of failure.

**Comment by alamb** [comment]
Thanks for the pointer to #331  👍  looks good

**Comment by alamb** [comment]
I also double checked the postgres and mysql manuals that the syntax in this PR is correct

**Comment by ever0de** [comment]
> I also double checked the postgres and mysql manuals that the syntax in this PR is correct

Is there any place to modify other than the test case?

**Review by alamb — APPROVED** [review]
Looks great @ever0de ! Thank you

**Pull request merged**
