### PR TITLE
Snowflake: support IGNORE/RESPECT NULLS inside function argument list

### PR DESCRIPTION
**Pull request by jmhain**
Just a tiny fix for a parsing failure I hit.

### CODE REVIEW

**Review by iffyio — APPROVED** [review]
LGTM! cc @alamb

**Review by alamb — APPROVED** [review]
Shall we add a test for this too so it doesn't get broken accidentally in a future release?

Thanks for the review @iffyio

**Comment by jmhain** [comment]
@alamb `parse_window_function_null_treatment_arg` currently covers this since it uses `all_dialects_where(|d| d.supports_window_function_null_treatment_arg())`. Or did you have some other idea for a test in mind?

**Comment by alamb** [comment]
> @alamb `parse_window_function_null_treatment_arg` currently covers this since it uses `all_dialects_where(|d| d.supports_window_function_null_treatment_arg())`. Or did you have some other idea for a test in mind?

What I was thinking was "if someone accidentally broke this feature in the future (by reverting this code, for example), there would be no test failure to let us know of the regression"

If you are fine with that risk I think we can merge this PR once its conflicts are resolved, given how small it is.

**Comment by jmhain** [comment]
@alamb Gotcha, added a Snowflake specific test and resolved the conflicts

**Review by alamb — APPROVED** [review]
Thanks @jmhain

**Pull request merged**
