### PR TITLE
Extend pivot operator support

### PR DESCRIPTION
**Pull request by iffyio**
Extends the parser with support for:

- Multiple aggregate function calls
- Aliased aggregation function calls
- Aliased pivot values - also allowing arbitrary expressions as values

https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#pivot_operator

### CODE REVIEW

**Comment by jmhain** [comment]
looks good to me! cc @alamb

**Review by alamb — APPROVED** [review]
LGTM -- thank you @iffyio  and @jmhain

**Comment by alamb** [comment]
🤔  github says this PR has conflicts that must be resolved 

Screenshot 2024-04-30 at 9 48 39 AM

**Comment by iffyio** [comment]
Resolved conflicts
thanks for the reviews @alamb @jmhain!

**Comment by alamb** [comment]
Thanks again

**Pull request merged**
