### PR TITLE
extract enum fields to named structs

### PR DESCRIPTION
**Pull request by cmoog**
Addresses #311 

Maybe it's appropriate to continue this refactor for `Expr` as well as the remaining `Statement` variants? Those seem much less pressing though since nearly all have <= 3 fields.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
This seems like a useful improvement to me (though as @cmoog  points out a fairly large backwards incompatible change which will cause pain for downstream crates)

Any other thoughts?

cc @Dandandan  and @andygrove

**Comment by Dandandan** [comment]
> Addresses #311
> 
> Maybe it's appropriate to continue this refactor for `Expr` as well as the remaining `Statement` variants? Those seem much less pressing though since nearly all have <= 3 fields.

Thank you for this PR.

I think it make sense if we do this, consistently do it for all statement variants.

I would be OK to not do the same thing for `Expr` now, I am not sure if there is a similar need to do it there too?

**Comment by alamb** [comment]
Closing old PRs. Please feel free to re-open if this was a mistake

**Comment by AugustoFKL** [comment]
@alamb @Dandandan I currently would love to have that approach, since my usage is requiring a lot of "unreachable!()" because of that.

Is that idea still OK? I can work on that this week

**Comment by alamb** [comment]
Hi @AugustoFKL  -- I think given that the sqlparser API is basically stable, I don't really want to contemplate such a large change at this time :(

**Pull request closed without merging**
