### PR TITLE
chore: remove redundant punctuation

### PR DESCRIPTION
**Pull request by Fischer0522**
related to #1433

### CODE REVIEW

**Comment by git-hulk** [comment]
@Fischer0522 You need to fix test cases as well. You can run `cargo test --all-features` on your side to check this.

**Comment by Fischer0522** [comment]
> @Fischer0522 Need to fix test cases as well. You can run `cargo test --all-features` on your side to check this.

done.

**Review by git-hulk — APPROVED** [review]
LGTM, cc @iffyio

**Review by alamb — APPROVED** [review]
Thank you @Fischer0522  and @git-hulk

**Comment by Fischer0522** [comment]
Can this pr be merged before next release? we are using sqlparser-rs in our project and this issue makes my leader mildly irritated @alamb

**Review by iffyio — APPROVED** [review]
LGTM!

**Comment by alamb** [comment]
> Can this pr be merged before next release? we are using sqlparser-rs in our project and this issue makes my leader mildly irritated @alamb

Of course! Thank you

**Pull request merged**
