### PR TITLE
fix: Support `expr` instead of `string` for argument to `interval`

### PR DESCRIPTION
**Pull request by togami2864**
In Big Query and MySQL, the following query is valid:
```
SELECT DATE_ADD(DATE "2008-12-25", INTERVAL 5 DAY);
```
https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_add
https://www.w3schools.com/mysql/func_mysql_date_add.asp

But now if the expression is number, an error occurred because the type of the value in `interval` is `String`
https://github.com/sqlparser-rs/sqlparser-rs/blob/ca15a4edbf1de4c00304b12e44d3adf9ac729406/src/ast/value.rs#L53

This PR replaces `String` with `Expr` to run correctly in `Interval`

One concern thing is that should I validate when the other dialect like `PostgresSQL`, `sqlite`. I don't know if the query is valid except for Big query and MySQL.

### CODE REVIEW

**Comment by 46bit** [comment]
Great to see this. There's related discussion in #298.

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @togami2864

**Comment by alamb** [comment]
@togami2864  -- there appear to be some CI failures

**Comment by togami2864** [comment]
@alamb I fixed all CI failures. Thanks.

**Pull request merged**
