### PR TITLE
Implement ON CONFLICT and RETURNING

### LINKED ISSUE #60: PostgreSQL RETURNING Data From Modified Rows
Postgresql [RETURNING](https://www.postgresql.org/docs/9.5/dml-returning.html)

```sql
INSERT INTO users (firstname, lastname) VALUES ('Joe', 'Cool') RETURNING id;

UPDATE products SET price = price * 1.10
  WHERE price <= 99.99
  RETURNING name, price AS new_price;

DELETE FROM products
  WHERE obsoletion_date = 'today'
  RETURNING *;
```
```rust
Err(ParserError("Expected end of statement, found: RETURNING"))
```

### PR DESCRIPTION
**Pull request by main--**
Implement the ON CONFLICT and RETURNING extensions as used in e.g. PostgreSQL and Sqlite.

Fixes #60.

### CODE REVIEW

**Comment by alamb** [comment]
CI is failing on this PR. Marking as draft

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @main--  Can you please add tests to this PR?

**Comment by baoyachi** [comment]
Is there any update 🦀 @alamb

**Comment by alamb** [comment]
Yes, I think this PR needs tests before it can be merged. Also I plan to invest some time today working down the outstanding sqlparser-rs review backlog. FYI @AugustoFKL

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @main--

**Pull request merged**
