### PR TITLE
Add MySql, BigQuery to all dialects

### LINKED ISSUE #690: Fix test-util `fn all_dialects()` to test all dialects actually
This is for internal but some fixes may be for users.

In [tests/sqlparser_common.rs](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/tests/sqlparser_common.rs) (⚠️ linked page may freeze your browser), a lot of test cases depend on [fn all_dialects()](https://github.com/sqlparser-rs/sqlparser-rs/blob/914810d36617581c2380ae9c0f501116a7d810b6/src/test_utils.rs#L135) to test all dialects.
But this `fn all_dialects()` doesn't include `MySqlDialect` and `BigQueryDialect` currently.
So we should include those to `all_dialects` and fix failed test cases after changing.

Change all_dialects to add MySqlDialect and BigQueryDialect ([src/test_utils.rs](https://github.com/sqlparser-rs/sqlparser-rs/blob/914810d36617581c2380ae9c0f501116a7d810b6/src/test_utils.rs#L135)): 
```rs
pub fn all_dialects() -> TestedDialects {
    TestedDialects {
        dialects: vec![
            Box::new(GenericDialect {}),
            Box::new(PostgreSqlDialect {}),
            Box::new(MsSqlDialect {}),
            Box::new(AnsiDialect {}),
            Box::new(SnowflakeDialect {}),
            Box::new(HiveDialect {}),
            Box::new(RedshiftSqlDialect {}),
            Box::new(MySqlDialect {}), // Added
            Box::new(BigQueryDialect {}), // Added
        ],
    }
}
```

Test results after changing above:
```
failures:
    parse_at_timezone
    parse_collate
    parse_collate_after_parens
    parse_delete_statement
    parse_delimited_identifiers
    parse_like
    parse_similar_to

test result: FAILED. 187 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s

error: test failed, to rerun pass '--test sqlparser_common'
```

### PR DESCRIPTION
**Pull request by omer-shtivi**
close #690

### CODE REVIEW

**Comment by omer-shtivi** [comment]
@AugustoFKL , @alamb 
MySql doesn't seem to support
```
SELECT "alias"."bar baz", "myfun"(), "simple id" AS "column alias" FROM "a table" AS "alias"
```
in test parse_delimited_identifiers
do you prefer to move this test to another dialect? or somehow exclude the MySql from all dialects?

**Comment by AugustoFKL** [comment]
@omer-shtivi I'd say to move the test, as MySQL doesn't accept 'x' as an identifier

Thanks for adding MySQL and BigQuery to all tests.

**Comment by omer-shtivi** [comment]
If we want to support parse_similar_to and parse_like in mysql, we need to support getting the an-escaped char.
For example:
``` sql
SELECT * FROM customers WHERE name {}LIKE '%a' ESCAPE '\'
```
at mysql needs to be:
``` sql
SELECT * FROM customers WHERE name {}LIKE '%a' ESCAPE '\\'
```
the `\` is escaped using double backslashes

**Comment by AugustoFKL** [comment]
@omer-shtivi I think this can be directed to another issue or PR.

**Review by AugustoFKL — CHANGES_REQUESTED** [review]
I think that LGTM.

@alamb ready for your look :)

This is in essence a little refactor, right @omer-shtivi ?

**Review by AugustoFKL — APPROVED** [review]
(sorry the previous comment, missclick)
I think that LGTM.

@alamb ready for your look :)

This is in essence a little refactor, right @omer-shtivi ?

**Comment by omer-shtivi** [comment]
Hi @AugustoFKL ,
Yes, it mainly testing refactor to support all dialects

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @omer-shtivi

**Pull request merged**
