### PR TITLE
use 2021 edition

### PR DESCRIPTION
**Pull request by Jimexist**
cc @andygrove and @Dandandan

### CODE REVIEW

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
looks like this resulted in couple new linting errors.

**Comment by alamb** [comment]
I merged main into this branch too and if it passes CI I'll merge this one in too

**Comment by alamb** [comment]
Last clippy warning: https://github.com/sqlparser-rs/sqlparser-rs/pull/374

**Comment by alamb** [comment]
Its now passing 🎉

**Pull request merged**
