### PR TITLE
Add an AST visitor

### PR DESCRIPTION
**Pull request by benesch**
Resubmission of #78, which caused some compilation failures due to merge skew when it landed. @andygrove are you game to try this again?

### CODE REVIEW

**Comment by malobre** [comment]
An AST visitor would be a nice thing to have.
@andygrove Could you consider merging this PR ?

**Comment by wseaton** [comment]
Bumping this, adding an AST visitor would make it much easier to use `sqlparser-rs` to extract particular metadata from queries like "what tables are referenced in this query".

@benesch I see you did some work on https://github.com/MaterializeInc/materialize/pull/3288 in auto-generating the visitor, is this something that could potentially be upstreamed, maybe have walkabout run on `pre-commit` hook to force the vistior to be regenerated?

**Comment by benesch** [comment]
Maybe! The build script approach, rather than the manual regeneration
approach, has been working well for us though. We could consider open
sourcing the walkabout crate on which the visitor generation depends, but I
don’t know that anyone at Materialize has much time to work on this at the
moment.

There’s an old PR from me on this repo somewhere that has a manual
implementation of the visitor, which might be of interest.

**Comment by alamb** [comment]
Hi @benesch  -- sorry for the delay in review. I am going to help out now with this repo and we are working to clear the backlog. Is this PR still something you would like to work on to help contribute?

**Comment by alamb** [comment]
Closing due to staleness -- feel free to reopen this PR or create a new one if you plan to keep working on this

**Pull request closed without merging**
