### PR TITLE
feat: add DECLARE parsing for mssql

### PR DESCRIPTION
**Pull request by devanbenz**
- Adds AST parsing support for `DECLARE` keyword [MsSql]
- Adds test for multiple variable declaration including a CURSOR and assignment declared scalar variable.

### CODE REVIEW

**Review by lovasoa — APPROVED** [review]

**Review by alamb — COMMENTED** [review]
Thanks @devanbenz  -- this PR looks good to me other than the CI failure 

https://github.com/sqlparser-rs/sqlparser-rs/actions/runs/8888752261/job/24428288785?pr=1235

It looks like a few simple clippy lints to fix

Also thank you @lovasoa  for the review

**Comment by devanbenz** [comment]
> Thanks @devanbenz -- this PR looks good to me other than the CI failure
> 
> [sqlparser-rs/sqlparser-rs/actions/runs/8888752261/job/24428288785?pr=1235](https://github.com/sqlparser-rs/sqlparser-rs/actions/runs/8888752261/job/24428288785?pr=1235)
> 
> It looks like a few simple clippy lints to fix
> 
> Also thank you @lovasoa for the review

Should be good now clippy is not showing any more linting problems.

**Comment by devanbenz** [comment]
@alamb okay cool, sorry about that. Should be good to go now ran all the ci checks locally with cargo.

**Comment by alamb** [comment]
> @alamb okay cool, sorry about that. Should be good to go now ran all the ci checks locally with cargo.

No worries -- thanks @devanbenz  for the contribution!

**Review by alamb — APPROVED** [review]

**Pull request merged**
