### PR TITLE
Fix the term 'Modulus' to 'Modulo'

### PR DESCRIPTION
**Pull request by MRGRAVITY817**
I've found out that the term for indicating `%` is currently `Modulus`, but I believe it should be `Modulo`.

Reference
---
- Definition of `Modulo`: https://en.wikipedia.org/wiki/Modulo_operation

### CODE REVIEW

**Review by alamb — APPROVED** [review]
I agree the proper term for the mathematical remainder operation is `Modulo` -- thanks @MRGRAVITY817 !

**Comment by alamb** [comment]
cc @Dandandan and @andygrove

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Thanks @MRGRAVITY817

**Comment by MRGRAVITY817** [comment]
> Thanks @MRGRAVITY817 

You're welcome 😀

**Pull request merged**
